In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pylab as pl
import scipy as sp
import sys
import openpyxl
import os, sys

%matplotlib inline

In [2]:
from box import Box
import glob

In [3]:
TOP = os.getcwd().replace("notebooks/tt", "")
D1 = TOP + 'data/'
figures_dir = TOP + 'manuscript/figures/'

In [4]:
df = pd.read_excel(D1+'unbalanced_all_190123.xlsx', sheet_name = 'all', index_col = [0])

In [5]:
df[df['tox'] == 'chr_liver'].describe()

,mean_f1,std_f1,mean_sensitivity,std_sensitivity,mean_specificity,std_specificity,mean_accuracy,std_accuracy,mean_precision,std_precision
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,0.728475,0.042200,0.804050,0.077850,0.316375,0.106650,0.632475,0.037275,0.687800,0.033325
std,0.084401,0.042175,0.164548,0.054683,0.203755,0.062572,0.054648,0.023754,0.041162,0.025022
min,0.461000,0.003000,0.385000,0.000000,0.000000,0.000000,0.442000,0.004000,0.586000,0.004000
25%,0.731250,0.019750,0.756000,0.038750,0.168250,0.071250,0.631750,0.023750,0.662000,0.015750
50%,0.751000,0.031000,0.822000,0.071000,0.343000,0.117000,0.648000,0.035000,0.689000,0.029000
75%,0.780250,0.053000,0.898500,0.114500,0.439000,0.135500,0.657500,0.049500,0.712500,0.044000
max,0.789000,0.173000,1.000000,0.200000,0.718000,0.235000,0.695000,0.112000,0.796000,0.114000

In [6]:
df[(df['tox'] == 'dev_liver') & (df['mean_f1'] >0)].describe()

,mean_f1,std_f1,mean_sensitivity,std_sensitivity,mean_specificity,std_specificity,mean_accuracy,std_accuracy,mean_precision,std_precision
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,0.083105,0.111895,0.073000,0.089421,0.925842,0.048211,0.785263,0.042789,0.172526,0.270895
std,0.050419,0.038375,0.094733,0.063330,0.099136,0.044798,0.069261,0.032167,0.085344,0.157294
min,0.027000,0.060000,0.022000,0.050000,0.558000,0.012000,0.540000,0.020000,0.033000,0.073000
25%,0.040000,0.078500,0.022000,0.050000,0.904000,0.023000,0.766500,0.021000,0.112000,0.126000
50%,0.082000,0.092000,0.067000,0.061000,0.969000,0.033000,0.813000,0.030000,0.163000,0.224000
75%,0.110000,0.153000,0.069000,0.101000,0.977000,0.053000,0.825000,0.044000,0.216500,0.447000
max,0.229000,0.165000,0.444000,0.324000,0.991000,0.175000,0.840000,0.132000,0.333000,0.471000